### ISSUE TITLE
[Possible FAQ / README entry] Differences between glimmer-dsl-web and glimmer-opal?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-web#1]
Heya Andy,

Since glimmer-dsl-web is new, no worries. But one question that came to me was: what is the difference
between these two? Or will glimmer-dsl-web integrate/include opal? If this were the case that would be
kind of interesting, e. g. write only ruby but also tap into effects induced and achieved by opal, without
people needing to write (or generate) javascript. Anyway, I believe if you get to it eventually, it may be
interesting to specify IF there are differences, if these are separate or not, stated in the README if you
ever get around to it.

**Comment by AndyObtiva** [comment]
I already explain the differences between glimmer-dsl-opal and glimmer-dsl-web in a paragraph at the beginning of the README.

Update: I just moved that paragraph to its own section (just search README for Glimmer DSL for Opal in case I move it again):
https://github.com/AndyObtiva/glimmer-dsl-web?tab=readme-ov-file#coming-from-glimmer-dsl-for-opal
