### ISSUE TITLE
[Screencast / Video] Basic glimmer-dsl-web usage (or rather, semi-basic) and FAQ entries

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-web#3]
Hey there Andy,

You recently announced glimmer-dsl-web here:

https://andymaleh.blogspot.com/2024/01/glimmer-goes-web.html

I actually did not see that in the last few days; new year still only slowly
starting for me.

You did some videos in the past.

Now, this takes time, and there is a time-cost ratio issue, so I am not necessarily
saying you should "do more videos".

But!

When I read through the description, I wondered what one can do with the
web-stuff, in particular the Form.

So my first request would be:

1) If you have time in the future, could you perhaps showcase a SIMPLE example,
ideally both via working code but also ONE video, not exceeding 5 minutes (or
whatever time frame you deem appropriate), **specifically** for how to use
a form. I don't mind which application it is, but something that could be semi-useful
such as adding new users to a database, via a form. And, also, that is important,
to show how to do so from zero (that is, ruby has been installed, but the other
things such as glimmer or opal, has NOT yet been installed).

This does not have to be super-complicated! Just a basic usage example, a bit
similar how people do so in rails. And less than 5 minutes should be fine, in
that people's attention span may not be super-great; plus, it also showcases
how this actually LOOKS on another computer (I think you have access to
OSX; I only have access to Linux and Windows and even then on Linux, the
things I use look very different to other users).

2) A few FAQ entries may be helpful specifically for the dsl-web stuff. For
instance, how does it relate to opal + wasm? I noticed you abandoned the
opal-specific parts, or perhaps integrated it into dsl-web. What about WASM
+ ruby? I believe this would be useful as a short FAQ entry. Does not have
to be long! A sentence or two should just suffice (if it is already there then
please disregard, but I did not find it).

Anyway.

I'll also close this, to not spam the issue tracker with open issues.

**Comment by AndyObtiva** [comment]
I already include tons of videos as gif files in the README. And, all your questions are answered in the README if you had read it completely. Please don’t ask questions next time until you’ve read all of the README as they’re otherwise just a waste of time and come across as trolling. Also, only ask practical questions about something you are stuck with after you tried the library not before.
